
[project]
name = "Toml Setup"
description = "Helps to config toml file properly"
author = "Senthilkumar"

[database]

# Nested `tables`
[environments]
  [environments.dev]
    ip = "10.0.0.1"
    loglevel = 'DEBUG'

  [environments.production]
    ip = "10.0.0.3"
    loglevel = 'DEBUG'

